In [ ]:
!pip install requests pandas

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.4.22)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import requests
import pandas as pd
import time

BASE_URL = "https://arctic-shift.photon-reddit.com/api/posts/search"

subreddit = "dubairealestate"

after_date = "2026-01-01T00:00:00Z"
before_date = "2026-04-30T23:59:59Z"

all_posts = []

current_before = before_date

while True:

    params = {
        "subreddit": subreddit,
        "after": after_date,
        "before": current_before,
        "limit": 100,
        "sort": "desc"
    }

    print(f"Fetching posts before {current_before}")

    response = requests.get(BASE_URL, params=params)

    if response.status_code != 200:
        print("Error:", response.status_code)
        break

    data = response.json()

    posts = data.get("data", [])

    if not posts:
        print("No more posts found.")
        break

    # SAVE ENTIRE RAW POSTS
    all_posts.extend(posts)

    # PAGINATION
    oldest_post = posts[-1]

    oldest_timestamp = oldest_post.get("created_utc")

    current_before = str(oldest_timestamp)

    print(f"Collected {len(all_posts)} total posts")

    time.sleep(1)

# CREATE DATAFRAME WITH ALL FIELDS
df = pd.DataFrame(all_posts)

# REMOVE DUPLICATES
#df.drop_duplicates(subset=["id"], inplace=True)

# EXPORT FULL RAW CSV
#df.to_csv("dubai_real_estate_raw_posts.csv", index=False)

print("DONE!")
#print(f"Saved {len(df)} posts")
print(f"Columns: {len(df.columns)}")
print(f"Rows: {len(df)}")
df.head(10)

Fetching posts before 2026-04-30T23:59:59Z
Collected 100 total posts
Fetching posts before 1777486792
Collected 200 total posts
Fetching posts before 1777395403
Collected 300 total posts
Fetching posts before 1777304701
Collected 400 total posts
Fetching posts before 1777198578
Collected 500 total posts
Fetching posts before 1777046706
Collected 600 total posts
Fetching posts before 1776959712
Collected 700 total posts
Fetching posts before 1776869600
Collected 800 total posts
Fetching posts before 1776764428
Collected 900 total posts
Fetching posts before 1776680582
Collected 1000 total posts
Fetching posts before 1776538395
Collected 1100 total posts
Fetching posts before 1776426265
Collected 1200 total posts
Fetching posts before 1776326814
Collected 1300 total posts
Fetching posts before 1776241628
Collected 1400 total posts
Fetching posts before 1776125645
Collected 1500 total posts
Fetching posts before 1776004919
Collected 1600 total posts
Fetching posts before 1775895172
Collected 1700 total posts
Fetching posts before 1775797628
Collected 1800 total posts
Fetching posts before 1775718762
Collected 1900 total posts
Fetching posts before 1775634368
Collected 2000 total posts
Fetching posts before 1775544736
Collected 2100 total posts
Fetching posts before 1775466978
Collected 2200 total posts
Fetching posts before 1775314723
Collected 2300 total posts
Fetching posts before 1775219765
Collected 2400 total posts
Fetching posts before 1775119374
Collected 2500 total posts
Fetching posts before 1775020368
Collected 2600 total posts
Fetching posts before 1774914308
Collected 2700 total posts
Fetching posts before 1774813732
Collected 2800 total posts
Fetching posts before 1774684517
Collected 2900 total posts
Fetching posts before 1774571914
Collected 3000 total posts
Fetching posts before 1774506754
Collected 3100 total posts
Fetching posts before 1774373920
Collected 3200 total posts
Fetching posts before 1774276016
Collected 3300 total posts
Fetching posts before 1774144111
Collected 3400 total posts
Fetching posts before 1773934129
Collected 3500 total posts
Fetching posts before 1773839739
Collected 3600 total posts
Fetching posts before 1773753224
Collected 3700 total posts
Fetching posts before 1773673765
Collected 3800 total posts
Fetching posts before 1773596173
Collected 3900 total posts
Fetching posts before 1773473649
Collected 4000 total posts
Fetching posts before 1773376173
Collected 4100 total posts
Fetching posts before 1773261157
Collected 4200 total posts
Fetching posts before 1773170611
Collected 4300 total posts
Fetching posts before 1773091976
Collected 4400 total posts
Fetching posts before 1772989019
Collected 4500 total posts
Fetching posts before 1772810526
Collected 4600 total posts
Fetching posts before 1772686282
Collected 4700 total posts
Fetching posts before 1772543846
Collected 4800 total posts
Fetching posts before 1772437987
Collected 4900 total posts
Fetching posts before 1772263498
Collected 5000 total posts
Fetching posts before 1772114025
Collected 5100 total posts
Fetching posts before 1772010215
Collected 5200 total posts
Fetching posts before 1771861482
Collected 5300 total posts
Fetching posts before 1771755069
Collected 5400 total posts
Fetching posts before 1771592141
Collected 5500 total posts
Fetching posts before 1771487858
Collected 5600 total posts
Fetching posts before 1771360080
Collected 5700 total posts
Fetching posts before 1771253353
Collected 5800 total posts
Fetching posts before 1771156329
Collected 5900 total posts
Fetching posts before 1770988927
Collected 6000 total posts
Fetching posts before 1770892902
Collected 6100 total posts
Fetching posts before 1770802047
Collected 6200 total posts
Fetching posts before 1770704653
Collected 6300 total posts
Fetching posts before 1770608678
Collected 6400 total posts
Fetching posts before 1770450276
Collected 6500 total posts
Fetching posts before 1770309378
Collected 6600 total posts
Fetching posts before 1770203421
Collected 6700 total posts
Fetching posts before 1770057350
Collected 6800 total posts
Fetching posts before 1769957383
Collected 6900 total posts
Fetching posts before 1769792164
Collected 7000 total posts
Fetching posts before 1769692415
Collected 7100 total posts
Fetching posts before 1769594051
Collected 7200 total posts
Fetching posts before 1769510770
Collected 7300 total posts
Fetching posts before 1769414773
Collected 7400 total posts
Fetching posts before 1769247697
Collected 7500 total posts
Fetching posts before 1769107421
Collected 7600 total posts
Fetching posts before 1768995229
Collected 7700 total posts
Fetching posts before 1768902374
Collected 7800 total posts
Fetching posts before 1768806051
Collected 7900 total posts
Fetching posts before 1768664874
Collected 8000 total posts
Fetching posts before 1768557197
Collected 8100 total posts
Fetching posts before 1768437145
Collected 8200 total posts
Fetching posts before 1768307529
Collected 8300 total posts
Fetching posts before 1768195697
Collected 8400 total posts
Fetching posts before 1767989863
Collected 8500 total posts
Fetching posts before 1767870444
Collected 8600 total posts
Fetching posts before 1767770549
Collected 8700 total posts
Fetching posts before 1767670742
Collected 8800 total posts
Fetching posts before 1767526524
Collected 8900 total posts
Fetching posts before 1767328146
Collected 8927 total posts
Fetching posts before 1767256921
No more posts found.
DONE!
Columns: 119
Rows: 8927

,_meta,all_awardings,allow_live_comments,approved_at_utc,approved_by,archived,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,wls,outbound_link,post_hint,preview,url_overridden_by_dest,media_metadata,gallery_data,is_gallery,poll_data,author_cakeday
0,"{'is_edited': True, 'retrieved_2nd_on': 177772...",[],False,None,None,False,Business_Archer_9697,None,None,[],...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,{'retrieved_2nd_on': 1777722323},[],False,None,None,False,Business_Archer_9697,None,None,[],...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'retrieved_2nd_on': 1777712754},[],False,None,None,False,SourceMost3079,None,None,[],...,6,"{'created': None, 'expiration': None, 'url': '...",image,"{'enabled': True, 'images': [{'id': 'iquku2v87...",https://i.redd.it/iquku2v87eyg1.png,NaN,NaN,NaN,NaN,NaN
3,"{'removal_type': 'deleted', 'retrieved_2nd_on'...",[],False,None,None,False,xxkurdistanpeshmerga,None,None,[],...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'retrieved_2nd_on': 1777703258},[],False,None,None,False,Outside-Cranberry-66,None,None,[],...,6,NaN,image,"{'enabled': True, 'images': [{'id': 'gabavpmoe...",https://i.redd.it/gabavpmoedyg1.jpeg,NaN,NaN,NaN,NaN,NaN
5,{'retrieved_2nd_on': 1777703229},[],False,None,None,False,Spare-Tie-8440,None,None,[],...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,{'retrieved_2nd_on': 1777702171},[],False,None,None,False,tech-dipson55,None,None,[],...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,{'retrieved_2nd_on': 1777699275},[],False,None,None,False,allthingsestate,None,None,[],...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"{'removal_type': 'deleted', 'retrieved_2nd_on'...",[],False,None,None,False,allthingsestate,None,None,[],...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,{'retrieved_2nd_on': 1777698203},[],False,None,None,False,[deleted],,None,NaN,...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df.to_csv('/content/drive/MyDrive/Dubai_Real_Estate_Data/reddit_data/full_raw_data.csv')

In [ ]:
import requests
import pandas as pd
import time

BASE_URL = "https://arctic-shift.photon-reddit.com/api/comments/search"

subreddit = "dubairealestate"

after_date = "2026-01-01T00:00:00Z"
before_date = "2026-04-30T23:59:59Z"

all_comments = []

current_before = before_date

while True:

    params = {
        "subreddit": subreddit,
        "after": after_date,
        "before": current_before,
        "limit": 100,
        "sort": "desc"
    }

    print(f"Fetching comments before {current_before}")

    response = requests.get(BASE_URL, params=params)

    if response.status_code != 200:
        print("Error:", response.status_code)
        break

    data = response.json()

    comments = data.get("data", [])

    if not comments:
        print("No more comments found.")
        break

    # SAVE ENTIRE RAW COMMENTS
    all_comments.extend(comments)

    # PAGINATION
    oldest_comment = comments[-1]

    oldest_timestamp = oldest_comment.get("created_utc")

    current_before = str(oldest_timestamp)

    print(f"Collected {len(all_comments)} total comments")

    time.sleep(1)

# CREATE DATAFRAME WITH ALL RAW FIELDS
df_comments = pd.DataFrame(all_comments)

# OPTIONAL DEDUPLICATION
# df.drop_duplicates(subset=["id"], inplace=True)

# EXPORT CSV
# df.to_csv(
#     "dubai_real_estate_raw_comments.csv",
#     index=False
# )

print("DONE!")
print(f"Columns: {len(df_comments.columns)}")
print(f"Rows: {len(df_comments)}")

df_comments.head(10)

Fetching comments before 2026-04-30T23:59:59Z
Collected 100 total comments
Fetching comments before 1777569971
Collected 200 total comments
Fetching comments before 1777558052
Collected 300 total comments
Fetching comments before 1777546843
Collected 400 total comments
Fetching comments before 1777536963
Collected 500 total comments
Fetching comments before 1777526327
Collected 600 total comments
Fetching comments before 1777492549
Collected 700 total comments
Fetching comments before 1777472966
Collected 800 total comments
Fetching comments before 1777460774
Collected 900 total comments
Fetching comments before 1777450784
Collected 1000 total comments
Fetching comments before 1777437143
Collected 1100 total comments
Fetching comments before 1777404699
Collected 1200 total comments
Fetching comments before 1777387706
Collected 1300 total comments
Fetching comments before 1777378159
Collected 1400 total comments
Fetching comments before 1777366735
Collected 1500 total comments
Fetching comments before 1777348612
Collected 1600 total comments
Fetching comments before 1777315157
Collected 1700 total comments
Fetching comments before 1777293929
Collected 1800 total comments
Fetching comments before 1777279788
Collected 1900 total comments
Fetching comments before 1777245085
Collected 2000 total comments
Fetching comments before 1777222276
Collected 2100 total comments
Fetching comments before 1777204384
Collected 2200 total comments
Fetching comments before 1777175606
Collected 2300 total comments
Fetching comments before 1777140183
Collected 2400 total comments
Fetching comments before 1777123953
Collected 2500 total comments
Fetching comments before 1777108924
Collected 2600 total comments
Fetching comments before 1777092615
Collected 2700 total comments
Fetching comments before 1777057129
Collected 2800 total comments
Fetching comments before 1777037268
Collected 2900 total comments
Fetching comments before 1777025642
Collected 3000 total comments
Fetching comments before 1777014788
Collected 3100 total comments
Fetching comments before 1777008734
Collected 3200 total comments
Fetching comments before 1776977438
Collected 3300 total comments
Fetching comments before 1776967719
Collected 3400 total comments
Fetching comments before 1776953089
Collected 3500 total comments
Fetching comments before 1776946258
Collected 3600 total comments
Fetching comments before 1776935922
Collected 3700 total comments
Fetching comments before 1776909698
Collected 3800 total comments
Fetching comments before 1776871168
Collected 3900 total comments
Fetching comments before 1776854747
Collected 4000 total comments
Fetching comments before 1776839742
Collected 4100 total comments
Fetching comments before 1776806416
Collected 4200 total comments
Fetching comments before 1776789406
Collected 4300 total comments
Fetching comments before 1776774543
Collected 4400 total comments
Fetching comments before 1776760556
Collected 4500 total comments
Fetching comments before 1776727067
Collected 4600 total comments
Fetching comments before 1776705627
Collected 4700 total comments
Fetching comments before 1776688626
Collected 4800 total comments
Fetching comments before 1776675294
Collected 4900 total comments
Fetching comments before 1776656229
Collected 5000 total comments
Fetching comments before 1776613507
Collected 5100 total comments
Fetching comments before 1776594296
Collected 5200 total comments
Fetching comments before 1776573946
Collected 5300 total comments
Fetching comments before 1776543461
Collected 5400 total comments
Fetching comments before 1776530168
Collected 5500 total comments
Fetching comments before 1776510403
Collected 5600 total comments
Fetching comments before 1776493445
Collected 5700 total comments
Fetching comments before 1776455952
Collected 5800 total comments
Fetching comments before 1776433270
Collected 5900 total comments
Fetching comments before 1776419612
Collected 6000 total comments
Fetching comments before 1776407219
Collected 6100 total comments
Fetching comments before 1776365363
Collected 6200 total comments
Fetching comments before 1776346271
Collected 6300 total comments
Fetching comments before 1776335566
Collected 6400 total comments
Fetching comments before 1776321029
Collected 6500 total comments
Fetching comments before 1776277542
Collected 6600 total comments
Fetching comments before 1776264241
Collected 6700 total comments
Fetching comments before 1776253165
Collected 6800 total comments
Fetching comments before 1776243029
Collected 6900 total comments
Fetching comments before 1776227621
Collected 7000 total comments
Fetching comments before 1776197303
Collected 7100 total comments
Fetching comments before 1776180292
Collected 7200 total comments
Fetching comments before 1776160049
Collected 7300 total comments
Fetching comments before 1776146100
Collected 7400 total comments
Fetching comments before 1776114764
Collected 7500 total comments
Fetching comments before 1776100045
Collected 7600 total comments
Fetching comments before 1776087293
Collected 7700 total comments
Fetching comments before 1776079761
Collected 7800 total comments
Fetching comments before 1776067856
Collected 7900 total comments
Fetching comments before 1776033099
Collected 8000 total comments
Fetching comments before 1776011415
Collected 8100 total comments
Fetching comments before 1775994205
Collected 8200 total comments
Fetching comments before 1775983099
Collected 8300 total comments
Fetching comments before 1775956783
Collected 8400 total comments
Fetching comments before 1775927419
Collected 8500 total comments
Fetching comments before 1775915373
Collected 8600 total comments
Fetching comments before 1775898638
Collected 8700 total comments
Fetching comments before 1775862571
Collected 8800 total comments
Fetching comments before 1775844681
Collected 8900 total comments
Fetching comments before 1775829477
Collected 9000 total comments
Fetching comments before 1775817350
Collected 9100 total comments
Fetching comments before 1775804344
Collected 9200 total comments
Fetching comments before 1775793971
Collected 9300 total comments
Fetching comments before 1775759369
Collected 9400 total comments
Fetching comments before 1775750609
Collected 9500 total comments
Fetching comments before 1775738342
Collected 9600 total comments
Fetching comments before 1775728603
Collected 9700 total comments
Fetching comments before 1775721664
Collected 9800 total comments
Fetching comments before 1775707884
Collected 9900 total comments
Fetching comments before 1775678015
Collected 10000 total comments
Fetching comments before 1775663928
Collected 10100 total comments
Fetching comments before 1775654483
Collected 10200 total comments
Fetching comments before 1775643165
Collected 10300 total comments
Fetching comments before 1775633608
Collected 10400 total comments
Fetching comments before 1775621197
Collected 10500 total comments
Fetching comments before 1775590676
Collected 10600 total comments
Fetching comments before 1775582348
Collected 10700 total comments
Fetching comments before 1775576697
Collected 10800 total comments
Fetching comments before 1775564216
Collected 10900 total comments
Fetching comments before 1775554747
Collected 11000 total comments
Fetching comments before 1775543680
Collected 11100 total comments
Fetching comments before 1775528795
Collected 11200 total comments
Fetching comments before 1775502369
Collected 11300 total comments
Fetching comments before 1775494882
Collected 11400 total comments
Fetching comments before 1775486872
Collected 11500 total comments
Fetching comments before 1775478878
Collected 11600 total comments
Fetching comments before 1775471508
Collected 11700 total comments
Fetching comments before 1775464998
Collected 11800 total comments
Fetching comments before 1775452849
Collected 11900 total comments
Fetching comments before 1775422948
Collected 12000 total comments
Fetching comments before 1775406732
Collected 12100 total comments
Fetching comments before 1775394240
Collected 12200 total comments
Fetching comments before 1775383917
Collected 12300 total comments
Fetching comments before 1775373048
Collected 12400 total comments
Fetching comments before 1775362186
Collected 12500 total comments
Fetching comments before 1775337045
Collected 12600 total comments
Fetching comments before 1775322032
Collected 12700 total comments
Fetching comments before 1775312793
Collected 12800 total comments
Fetching comments before 1775302106
Collected 12900 total comments
Fetching comments before 1775293561
Collected 13000 total comments
Fetching comments before 1775283765
Collected 13100 total comments
Fetching comments before 1775251436
Collected 13200 total comments
Fetching comments before 1775237531
Collected 13300 total comments
Fetching comments before 1775229135
Collected 13400 total comments
Fetching comments before 1775219289
Collected 13500 total comments
Fetching comments before 1775210776
Collected 13600 total comments
Fetching comments before 1775202267
Collected 13700 total comments
Fetching comments before 1775194849
Collected 13800 total comments
Fetching comments before 1775161388
Collected 13900 total comments
Fetching comments before 1775152866
Collected 14000 total comments
Fetching comments before 1775144341
Collected 14100 total comments
Fetching comments before 1775135483
Collected 14200 total comments
Fetching comments before 1775128800
Collected 14300 total comments
Fetching comments before 1775118153
Collected 14400 total comments
Fetching comments before 1775097909
Collected 14500 total comments
Fetching comments before 1775067459
Collected 14600 total comments
Fetching comments before 1775061665
Collected 14700 total comments
Fetching comments before 1775050499
Collected 14800 total comments
Fetching comments before 1775044903
Collected 14900 total comments
Fetching comments before 1775036468
Collected 15000 total comments
Fetching comments before 1775027909
Collected 15100 total comments
Fetching comments before 1775014965
Collected 15200 total comments
Fetching comments before 1774989114
Collected 15300 total comments
Fetching comments before 1774974413
Collected 15400 total comments
Fetching comments before 1774968662
Collected 15500 total comments
Fetching comments before 1774963830
Collected 15600 total comments
Fetching comments before 1774957134
Collected 15700 total comments
Fetching comments before 1774946186
Collected 15800 total comments
Fetching comments before 1774936642
Collected 15900 total comments
Fetching comments before 1774913012
Collected 16000 total comments
Fetching comments before 1774893371
Collected 16100 total comments
Fetching comments before 1774883119
Collected 16200 total comments
Fetching comments before 1774871324
Collected 16300 total comments
Fetching comments before 1774864973
Collected 16400 total comments
Fetching comments before 1774859979
Collected 16500 total comments
Fetching comments before 1774848455
Collected 16600 total comments
Fetching comments before 1774827091
Collected 16700 total comments
Fetching comments before 1774813093
Collected 16800 total comments
Fetching comments before 1774798313
Collected 16900 total comments
Fetching comments before 1774789046
Collected 17000 total comments
Fetching comments before 1774778542
Collected 17100 total comments
Fetching comments before 1774768795
Collected 17200 total comments
Fetching comments before 1774740487
Collected 17300 total comments
Fetching comments before 1774723985
Collected 17400 total comments
Fetching comments before 1774711493
Collected 17500 total comments
Fetching comments before 1774699873
Collected 17600 total comments
Fetching comments before 1774692542
Collected 17700 total comments
Fetching comments before 1774685508
Collected 17800 total comments
Fetching comments before 1774675108
Collected 17900 total comments
Fetching comments before 1774652589
Collected 18000 total comments
Fetching comments before 1774642211
Collected 18100 total comments
Fetching comments before 1774632494
Collected 18200 total comments
Fetching comments before 1774624284
Collected 18300 total comments
Fetching comments before 1774615111
Collected 18400 total comments
Fetching comments before 1774608441
Collected 18500 total comments
Fetching comments before 1774602376
Collected 18600 total comments
Fetching comments before 1774595756
Collected 18700 total comments
Fetching comments before 1774590706
Collected 18800 total comments
Fetching comments before 1774572811
Collected 18900 total comments
Fetching comments before 1774556981
Collected 19000 total comments
Fetching comments before 1774547780
Collected 19100 total comments
Fetching comments before 1774538545
Collected 19200 total comments
Fetching comments before 1774531851
Collected 19300 total comments
Fetching comments before 1774524785
Collected 19400 total comments
Fetching comments before 1774517983
Collected 19500 total comments
Fetching comments before 1774509643
Collected 19600 total comments
Fetching comments before 1774500247
Collected 19700 total comments
Fetching comments before 1774476977
Collected 19800 total comments
Fetching comments before 1774465376
Collected 19900 total comments
Fetching comments before 1774451461
Collected 20000 total comments
Fetching comments before 1774441652
Collected 20100 total comments
Fetching comments before 1774435062
Collected 20200 total comments
Fetching comments before 1774428547
Collected 20300 total comments
Fetching comments before 1774421168
Collected 20400 total comments
Fetching comments before 1774406498
Collected 20500 total comments
Fetching comments before 1774385627
Collected 20600 total comments
Fetching comments before 1774375007
Collected 20700 total comments
Fetching comments before 1774365697
Collected 20800 total comments
Fetching comments before 1774356826
Collected 20900 total comments
Fetching comments before 1774350300
Collected 21000 total comments
Fetching comments before 1774340609
Collected 21100 total comments
Fetching comments before 1774330908
Collected 21200 total comments
Fetching comments before 1774303654
Collected 21300 total comments
Fetching comments before 1774290651
Collected 21400 total comments
Fetching comments before 1774282146
Collected 21500 total comments
Fetching comments before 1774275652
Collected 21600 total comments
Fetching comments before 1774269330
Collected 21700 total comments
Fetching comments before 1774263827
Collected 21800 total comments
Fetching comments before 1774257829
Collected 21900 total comments
Fetching comments before 1774249848
Collected 22000 total comments
Fetching comments before 1774219201
Collected 22100 total comments
Fetching comments before 1774207352
Collected 22200 total comments
Fetching comments before 1774195406
Collected 22300 total comments
Fetching comments before 1774185027
Collected 22400 total comments
Fetching comments before 1774171187
Collected 22500 total comments
Fetching comments before 1774144645
Collected 22600 total comments
Fetching comments before 1774119392
Collected 22700 total comments
Fetching comments before 1774102130
Collected 22800 total comments
Fetching comments before 1774091604
Collected 22900 total comments
Fetching comments before 1774084347
Collected 23000 total comments
Fetching comments before 1774069776
Collected 23100 total comments
Fetching comments before 1774040883
Collected 23200 total comments
Fetching comments before 1774025785
Collected 23300 total comments
Fetching comments before 1774010766
Collected 23400 total comments
Fetching comments before 1773998819
Collected 23500 total comments
Fetching comments before 1773987437
Collected 23600 total comments
Fetching comments before 1773972721
Collected 23700 total comments
Fetching comments before 1773957792
Collected 23800 total comments
Fetching comments before 1773950898
Collected 23900 total comments
Fetching comments before 1773940844
Collected 24000 total comments
Fetching comments before 1773930572
Collected 24100 total comments
Fetching comments before 1773917644
Collected 24200 total comments
Fetching comments before 1773907511
Collected 24300 total comments
Fetching comments before 1773891380
Collected 24400 total comments
Fetching comments before 1773869782
Collected 24500 total comments
Fetching comments before 1773862277
Collected 24600 total comments
Fetching comments before 1773852922
Collected 24700 total comments
Fetching comments before 1773843010
Collected 24800 total comments
Fetching comments before 1773836677
Collected 24900 total comments
Fetching comments before 1773829418
Collected 25000 total comments
Fetching comments before 1773823367
Collected 25100 total comments
Fetching comments before 1773816738
Collected 25200 total comments
Fetching comments before 1773809020
Collected 25300 total comments
Fetching comments before 1773797345
Collected 25400 total comments
Fetching comments before 1773787699
Collected 25500 total comments
Fetching comments before 1773778529
Collected 25600 total comments
Fetching comments before 1773769286
Collected 25700 total comments
Fetching comments before 1773760987
Collected 25800 total comments
Fetching comments before 1773754235
Collected 25900 total comments
Fetching comments before 1773747627
Collected 26000 total comments
Fetching comments before 1773740968
Collected 26100 total comments
Fetching comments before 1773733130
Collected 26200 total comments
Fetching comments before 1773725311
Collected 26300 total comments
Fetching comments before 1773706444
Collected 26400 total comments
Fetching comments before 1773692926
Collected 26500 total comments
Fetching comments before 1773682508
Collected 26600 total comments
Fetching comments before 1773673954
Collected 26700 total comments
Fetching comments before 1773664029
Collected 26800 total comments
Fetching comments before 1773657961
Collected 26900 total comments
Fetching comments before 1773651637
Collected 27000 total comments
Fetching comments before 1773645005
Collected 27100 total comments
Fetching comments before 1773637278
Collected 27200 total comments
Fetching comments before 1773615110
Collected 27300 total comments
Fetching comments before 1773606653
Collected 27400 total comments
Fetching comments before 1773595507
Collected 27500 total comments
Fetching comments before 1773582039
Collected 27600 total comments
Fetching comments before 1773572306
Collected 27700 total comments
Fetching comments before 1773562592
Collected 27800 total comments
Fetching comments before 1773550663
Collected 27900 total comments
Fetching comments before 1773529272
Collected 28000 total comments
Fetching comments before 1773512716
Collected 28100 total comments
Fetching comments before 1773501308
Collected 28200 total comments
Fetching comments before 1773492290
Collected 28300 total comments
Fetching comments before 1773487025
Collected 28400 total comments
Fetching comments before 1773479189
Collected 28500 total comments
Fetching comments before 1773468663
Collected 28600 total comments
Fetching comments before 1773446283
Collected 28700 total comments
Fetching comments before 1773428444
Collected 28800 total comments
Fetching comments before 1773422124
Collected 28900 total comments
Fetching comments before 1773410435
Collected 29000 total comments
Fetching comments before 1773402254
Collected 29100 total comments
Fetching comments before 1773393609
Collected 29200 total comments
Fetching comments before 1773385172
Collected 29300 total comments
Fetching comments before 1773367333
Collected 29400 total comments
Fetching comments before 1773349326
Collected 29500 total comments
Fetching comments before 1773343041
Collected 29600 total comments
Fetching comments before 1773338284
Collected 29700 total comments
Fetching comments before 1773331736
Collected 29800 total comments
Fetching comments before 1773321932
Collected 29900 total comments
Fetching comments before 1773311237

,_meta,all_awardings,approved_at_utc,approved_by,archived,associated_award,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,subreddit_type,top_awarded_type,total_awards_received,treatment_tags,unrepliable_reason,ups,user_reports,media_metadata,author_cakeday,editable
0,{'retrieved_2nd_on': 1777722544},[],None,None,False,None,rookieking11,None,None,[],...,public,None,0,[],None,1,[],NaN,NaN,NaN
1,{'retrieved_2nd_on': 1777722323},[],None,None,False,None,AutoModerator,None,None,[],...,public,None,0,[],None,1,[],NaN,NaN,NaN
2,{'retrieved_2nd_on': 1777721085},[],None,None,False,None,SnooComics8268,None,None,[],...,public,None,0,[],None,2,[],NaN,NaN,NaN
3,{'retrieved_2nd_on': 1777721090},[],None,None,False,None,Medium-Magician5285,None,None,[],...,public,None,0,[],None,2,[],NaN,NaN,NaN
4,{'retrieved_2nd_on': 1777719315},[],None,None,False,None,sylvyannn,None,None,[],...,public,None,0,[],None,1,[],NaN,NaN,NaN
5,{'retrieved_2nd_on': 1777719184},[],None,None,False,None,callme-etsh,None,None,[],...,public,None,0,[],None,1,[],NaN,NaN,NaN
6,{'retrieved_2nd_on': 1777718542},[],None,None,False,None,RadioactiveHotshot,None,None,[],...,public,None,0,[],None,2,[],NaN,NaN,NaN
7,{'retrieved_2nd_on': 1777718357},[],None,None,False,None,Goyim5,None,None,[],...,public,None,0,[],None,-5,[],NaN,NaN,NaN
8,{'retrieved_2nd_on': 1777717278},[],None,None,False,None,sylvyannn,None,None,[],...,public,None,0,[],None,1,[],NaN,NaN,NaN
9,{'retrieved_2nd_on': 1777716847},[],None,None,False,None,sylvyannn,None,None,[],...,public,None,0,[],None,1,[],NaN,NaN,NaN

In [ ]:
df_comments.to_csv('/content/drive/MyDrive/Dubai_Real_Estate_Data/reddit_data/full_raw_comments.csv')